name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to publish
        required: false
        default: ''
        type: string
      force:
        description: Force publish
        required: false
        default: false
        type: boolean
  push:
    tags:
      - '[0-1].[0-9]+.[0-9]+'

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: LuaRocks Publish
        uses: MunifTanjim/luarocks-publish-action@feat-initial-implementation
        with:
          lua_version: 5.1.5
          luarocks_version: 3.9.1
          version: ${{ inputs.version }}
          force: ${{ inputs.force }}
