name: Publish

on:
  push:
    tags:
      - '[0-1].[0-9]+.[0-9]+'

jobs:
  publish:
    name: release
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    needs:
      - lint
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: LuaRocks Publish
        uses: MunifTanjim/luarocks-publish-action@feat-initial-implementation
        with:
          lua_version: 5.1.5
          luarocks_version: 3.9.1
